### ISSUE TITLE
Example project where the library gets used inside Godot

### ISSUE THREAD

**Issue by marcello505** [marcello505/godot-ggrs-wrapper#13]
While i've done simple quick start guide to show how the library works, having an actual example project is probably a better way of showing the library in action.

**Comment by trian-gles** [comment]
I'd like to start working on this over the weekend!

**Comment by marcello505** [comment]
Appreciated! Feel free to ask any questions you may have!

**Comment by trian-gles** [comment]
[How does this look?](https://github.com/trian-gles/godot-ggrs-wrapper/tree/example/example)
I mostly used the README code and made it super simple.  I could also implement handling for the other GGRS events, or make an actual game.

**Comment by marcello505** [comment]
I've read through the code and it looks good, great job man. I'll open it up in godot tomorrow to see how it looks in action.

> I could also implement handling for the other GGRS events, or make an actual game.

I think it's fine if it remains simple like this, explaining the basics is the important part here. At most the comments could be adjusted to refer to the documentation so that people can read up on it further if they want to. Could you make a pull request for this branch?

Lastly i noticed one of your projects on GitHub uses this project, if you want i could add a "used by" section to the `README.MD` where i could link your game. Only if you want to ofc

**Comment by trian-gles** [comment]
PR submitted!

A mention of my project would be great, I'll add a link back to this repo as well.

**Comment by marcello505** [comment]
I've merged #15 and added a link to Girls With Sword. I also added an entry in the changelog where I've credited your addition. Thank you once again for your contribution :+1:
